convert DB and RE routine checks to take command-line arguments

diff --git a/dist/configure.in b/dist/configure.in
--- a/dist/configure.in
+++ b/dist/configure.in
@@ -1,4 +1,4 @@
-dnl	$Id: configure.in,v 8.14 1996/02/25 11:50:21 bostic Exp $ (Berkeley) $Date: 1996/02/25 11:50:21 $
+dnl	$Id: configure.in,v 8.15 1996/02/25 12:08:07 bostic Exp $ (Berkeley) $Date: 1996/02/25 12:08:07 $
 
 dnl Process this file with autoconf to produce a configure script.
 AC_INIT(configure)
@@ -215,6 +215,7 @@ if test "$vi_cv_ftruncate" = chsize; then
 	AC_DEFINE(HAVE_FTRUNCATE_CHSIZE)
 fi
 if test "$vi_cv_ftruncate" = no; then
+	echo
 	echo "Fatal error: no file truncation system call."
 	exit 1
 fi
@@ -350,39 +351,65 @@ if test "$vi_cv_sprintf_count" = no; then
 fi
 AC_MSG_RESULT($vi_cv_sprintf_count)
 
-dnl Check for local DB.
+dnl Check for C library DB routines.
 dnl XXX
-dnl Some older versions of DB can't handle vi, so, for now, always
-dnl compile it in.
+dnl Some older versions of DB can't handle vi, so, for now, always compile
+dnl it in, unless the user specifies on the command line that we're to use
+dnl the C library one.
 AC_SUBST(dbinc)
 AC_SUBST(dbobjs)
 AC_MSG_CHECKING(for Berkeley DB package)
 AC_CACHE_VAL(vi_cv_db_lib, [dnl
-AC_TRY_LINK([#include <db.h>], [dbopen("a", 0, 0, 0, 0);],
-	[vi_cv_db_lib=yes], [vi_cv_db_lib=no])])
-if test "$vi_cv_db_lib" != NOMATCH; then
+AC_ARG_WITH(db,
+	[  --with-db=library|vi    library: Use the DB routines in the C library.
+                          vi:      Use the vi-provided DB routines],
+	[if test $withval = "library"; then
+		vi_cv_db_lib="C library DB routines"
+	else
+	if test $withval = "vi"; then
+		vi_cv_db_lib="vi DB routines"
+	else
+		echo
+		echo "Fatal error: with-db may only be \"library\" or \"vi\"."
+		exit 1
+	fi
+	fi], [vi_cv_db_lib="vi DB routines"])])
+if test "$vi_cv_db_lib" = "vi DB routines"; then
 	dbinc="-I../db/include"
 	dbobjs=\$\{DBOBJS\}
 fi
 AC_MSG_RESULT($vi_cv_db_lib)
 
-dnl Check for local RE routines.
+dnl Check for C library RE routines.
 dnl XXX
-dnl Need to make sure that they have Henry's word-search extensions.
-dnl So, for now, always compile it in.
+dnl Need to have Henry's word-search extensions, so for now, always compile
+dnl it in, unless the user specifies on the command line that we're to use
+dnl the C library one.
 AC_SUBST(reinc)
 AC_SUBST(reobjs)
 AC_MSG_CHECKING(for POSIX 1003.2 RE routines)
 AC_CACHE_VAL(vi_cv_re_lib, [dnl
-AC_TRY_LINK([#include <regex.h>], [regerror(0, 0, 0, 0);],
-	[vi_cv_re_lib=yes], [vi_cv_re_lib=no])])
-if test "$vi_cv_re_lib" != NOMATCH; then
+AC_ARG_WITH(re, 
+	[  --with-re=library|vi    library: Use the RE routines in the C library.
+                          vi:      Use the vi-provided RE routines],
+	[if test $withval = "library"; then
+		vi_cv_re_lib="C library RE routines"
+	else
+	if test $withval = "vi"; then
+		vi_cv_re_lib="vi RE routines"
+	else
+		echo
+		echo "Fatal error: with-re may only be \"library\" or \"vi\"."
+		exit 1
+	fi
+	fi], [vi_cv_re_lib="vi RE routines"])])
+if test "$vi_cv_re_lib" = "vi RE routines"; then
 	reinc="-I../regex"
 	reobjs=\$\{REOBJS\}
 fi
 AC_MSG_RESULT($vi_cv_re_lib)
 
-dnl DB uses specific integer sizes.
+dnl DB/Vi uses specific integer sizes.
 AC_SUBST(u_int8_decl)
 AC_MSG_CHECKING(for u_int8_t)
 AC_CACHE_VAL(vi_cv_uint8, [dnl
@@ -392,6 +419,7 @@ AC_TRY_RUN([main(){exit(sizeof(unsigned char) != 1);}],
 	[vi_cv_uint8="unsigned char"], [vi_cv_uint8=no]))])
 AC_MSG_RESULT($vi_cv_uint8)
 if test "$vi_cv_uint8" = no; then
+	echo
 	echo "Fatal error: no unsigned, 8-bit integral type."
 	exit 1
 fi
@@ -410,6 +438,7 @@ AC_TRY_RUN([main(){exit(sizeof(unsigned int) != 2);}],
 	[vi_cv_uint16="unsigned int"], [vi_cv_uint16=no])))])
 AC_MSG_RESULT($vi_cv_uint16)
 if test "$vi_cv_uint16" = no; then
+	echo
 	echo "Fatal error: no unsigned, 16-bit integral type."
 	exit 1
 fi
@@ -428,6 +457,7 @@ AC_TRY_RUN([main(){exit(sizeof(int) != 2);}],
 	[vi_cv_int16="int"], [vi_cv_int16=no])))])
 AC_MSG_RESULT($vi_cv_int16)
 if test "$vi_cv_int16" = no; then
+	echo
 	echo "Fatal error: no signed, 16-bit integral type."
 	exit 1
 fi
@@ -446,6 +476,7 @@ AC_TRY_RUN([main(){exit(sizeof(unsigned long) != 4);}],
 	[vi_cv_uint32="unsigned long"], [vi_cv_uint32=no])))])
 AC_MSG_RESULT($vi_cv_uint32)
 if test "$vi_cv_uint32" = no; then
+	echo
 	echo "Fatal error: no unsigned, 32-bit integral type."
 	exit 1
 fi
@@ -464,6 +495,7 @@ AC_TRY_RUN([main(){exit(sizeof(long) != 4);}],
 	[vi_cv_int32="long"], [vi_cv_int32=no])))])
 AC_MSG_RESULT($vi_cv_int32)
 if test "$vi_cv_int32" = no; then
+	echo
 	echo "Fatal error: no signed, 32-bit integral type."
 	exit 1
 fi
