We have to have gcc 2.x on LynxOS, so check for it.

diff --git a/dist/configure.in b/dist/configure.in
--- a/dist/configure.in
+++ b/dist/configure.in
@@ -1,4 +1,4 @@
-dnl	$Id: configure.in,v 8.130 1996/09/25 17:27:04 bostic Exp $ (Berkeley) $Date: 1996/09/25 17:27:04 $
+dnl	$Id: configure.in,v 8.131 1996/10/10 20:11:58 bostic Exp $ (Berkeley) $Date: 1996/10/10 20:11:58 $
 
 dnl Process this file with autoconf to produce a configure script.
 AC_INIT(../common/main.c)
@@ -29,7 +29,9 @@ dnl XXX
 dnl Don't override anything if it's already set from the environment.
 
 dnl Compiler, preprocessor and load flags.
-dnl AUX: -ZP disables _BSD_SOURCE et al, but enables POSIX at link time.
+dnl AUX:	-ZP disables _BSD_SOURCE et al, but enables POSIX at link time.
+dnl LynxOS:	We check for gcc 2.x or better, the gcc 1 that was shipped with
+dnl		LynxOS historically wasn't good enough.
 AC_SUBST(CPPFLAGS)
 case "$host_os" in
 aix3.2.5)  OPTFLAG=${OPTFLAG-"-O"};;
@@ -43,6 +45,18 @@ bsdi*)	   CC=${CC-"shlicc"}
 	   OPTFLAG=${OPTFLAG-"-O2"};;
 irix6*)	   OPTFLAG=${OPTFLAG-"-O2"};;
 irix*)	   OPTFLAG=${OPTFLAG-"-O2"};;
+lynxos*)   AC_MSG_CHECKING([for GNU C (gcc) version 2.x])
+	   ac_cv_gcc_vers=`${CC-cc} -v 2>&1 | \
+		grep "gcc version " | sed 's/.*version //'`
+	   ac_cv_gcc_major=`echo "$ac_cv_gcc_vers" | sed 's/\..*//'`
+	   if test "$ac_cv_gcc_major" = "2" ; then
+		AC_MSG_RESULT(yes)
+	   else
+		AC_MSG_RESULT(no)
+		echo "Fatal error: Nvi requires gcc 2.x to build on LynxOS."
+		echo "See build/README.LynxOS for more information."
+		exit 1
+	   fi;;
 nextstep3) CPPFLAGS=${CPPFLAGS-"-w -pipe -posix"}
 	   LDFLAGS=${LDFLAGS-"-posix"}
 	   OPTFLAG=${OPTFLAG-"-O9"};;
