don't set CC if it's already set in the environment make tknvi take a different set of LIBS (TKLIBS) make the Tk/Tcl interpreter separately enabled using --enable-tclinterp

diff --git a/dist/configure.in b/dist/configure.in
--- a/dist/configure.in
+++ b/dist/configure.in
@@ -1,4 +1,4 @@
-dnl	$Id: configure.in,v 8.42 1996/02/27 20:55:10 bostic Exp $ (Berkeley) $Date: 1996/02/27 20:55:10 $
+dnl	$Id: configure.in,v 8.43 1996/02/28 18:45:02 bostic Exp $ (Berkeley) $Date: 1996/02/28 18:45:02 $
 
 dnl Process this file with autoconf to produce a configure script.
 AC_INIT(configure)
@@ -27,7 +27,7 @@ aux*)	  CFLAGS=${CFLAGS-"-O"}
 	  LIBOBJS="getopt.o strpbrk.o $LIBOBJS";;
 bsd4\.4)  CFLAGS=${CFLAGS-"-O2"}
 	  LIBS="-lutil $LIBS";;
-bsdi2\.1) CC=shlicc
+bsdi2\.1) CC=${CC-"shlicc"}
 	  CFLAGS=${CFLAGS-"-O2"}
 	  LIBS="-lipc $LIBS";;
 bsdi*)	  CFLAGS=${CFLAGS-"-O2"};;
@@ -41,12 +41,14 @@ netbsd*)  LIBS="-lutil $LIBS";;
 ptx*)	  LIBS="-lseq -linet -lsocket $LIBS";;
 sinix*)	  LIBS="-lelf -lc $LIBS";;
 wgs*)	  LIBS="-lnsl $LIBS";;
-*)	  CFLAGS=${CFLAGS-"-O"};;
 esac
 
 dnl The default compiler is cc.
 AC_SUBST(CC)
 CC=${CC-cc}
+
+dnl The default CFLAGS is -O
+CFLAGS=${CFLAGS-"-O"}
 
 dnl Checks for programs.
 SAVED_PATH=$PATH
@@ -97,28 +99,44 @@ if test "$no_x" != yes; then
 	fi
 fi
 
-dnl Check to see if we can load a Tcl interpreter and Tk vi front-end.
-dnl If we can, then both nvi and tknvi have the same load libraries.
-dnl If we can't, then nvi doesn't want to load the X libraries, and we
-dnl don't care about tknvi.
+dnl Check to see if the Tcl/Tk libraries exist and we can load the Tk
+dnl vi front-end.  The tknvi libs (TKLIBS) start off the same as LIBS.
 AC_SUBST(tknvi)
+AC_SUBST(TKLIBS)
 SAVED_CPPFLAGS="$CPPFLAGS"
 CPPFLAGS="-I/usr/local/include $XINCS $CPPFLAGS"
 SAVED_LIBS="$LIBS"
-LIBS="-L/usr/local/lib -ltk -ltcl -lm $XLIBS $LIBS"
-
-AC_MSG_CHECKING(for Tcl interpreter)
+LIBS="-L/usr/contrib/lib -L/usr/local/lib -ltk -ltcl -lm $XLIBS $LIBS"
+AC_MSG_CHECKING(for Tcl/Tk libraries)
 AC_CACHE_VAL(vi_cv_tcltk, [dnl
 AC_TRY_LINK([#include <tcl.h>], [Tcl_Eval(0, 0);],
 	[vi_cv_tcltk=yes], [vi_cv_tcltk=no])])
 if test "$vi_cv_tcltk" = yes; then
 	tknvi=tknvi
-	AC_DEFINE(HAVE_TCL_INTERP)
+	TKLIBS=$LIBS
 else
 	CPPFLAGS=$SAVED_CPPFLAGS
-	LIBS=$SAVED_LIBS
 fi
+LIBS=$SAVED_LIBS
 AC_MSG_RESULT($vi_cv_tcltk)
+
+dnl If the user wants a Tcl/Tk interpreter in nvi, load it.
+AC_MSG_CHECKING(for Tcl/Tk interpreter)
+AC_CACHE_VAL(vi_cv_tclinterp, [dnl
+AC_ARG_ENABLE(tclinterp,
+	[  --enable-tclinterp      Compile a Tcl/Tk interpreter into vi.],
+	[vi_cv_tclinterp="yes"], [vi_cv_tclinterp="no"])])
+if test "$vi_cv_tclinterp" = yes; then
+	if test "$vi_cv_tcltk" = yes; then
+		LIBS=$TKLIBS
+		AC_DEFINE(HAVE_TCL_INTERP)
+	else
+		echo
+		echo "Fatal error: the Tcl/Tk libraries not found."
+		exit 1
+	fi
+fi
+AC_MSG_RESULT($vi_cv_tclinterp)
 
 dnl Check for the termcap/termlib library.
 AC_CHECK_LIB(termlib, tgetent,
@@ -137,17 +155,17 @@ AC_MSG_CHECKING(for curses library)
 AC_CACHE_VAL(vi_cv_curses, [dnl
 AC_ARG_WITH(curses,
 	[  --with-curses=ask|system|vi
-                          ask:    Prompt for the curses library to use.
-                          system: Use the system curses library.
-                          vi:     Use the vi-provided curses library],
+                          ask:     Prompt for the curses library to use.
+                          system:  Use the system curses library.
+                          vi:      Use the vi-provided curses library],
 	[if test "$withval" = ask; then
 		vi_cv_curses="user specified"
 	else
-	if test "$withval" = system; then
-		vi_cv_curses="system curses"
-	else
-		vi_cv_curses="vi curses"
-	fi
+		if test "$withval" = system; then
+			vi_cv_curses="system curses"
+		else
+			vi_cv_curses="vi curses"
+		fi
 	fi], [vi_cv_curses="vi curses"])
 if test "$vi_cv_curses" = "user specified"; then
 AC_TRY_RUN([#include <stdio.h>
@@ -458,8 +476,9 @@ if test "$vi_cv_db_hash_open" = "C library"; then
 	AC_DEFINE(HAVE_DB_HASH_OPEN)
 fi
 if test "$vi_cv_db_hash_open" = "DB library"; then
-	AC_DEFINE(HAVE_DB_HASH_OPEN)
 	LIBS="-ldb $LIBS"
+	TKLIBS="-ldb $TKLIBS"
+	AC_DEFINE(HAVE_DB_HASH_OPEN)
 fi
 AC_MSG_RESULT($vi_cv_db_hash_open)
 
