use perl5 output information to configure in perl5 interpreter

diff --git a/dist/configure.in b/dist/configure.in
--- a/dist/configure.in
+++ b/dist/configure.in
@@ -1,4 +1,4 @@
-dnl	$Id: configure.in,v 8.55 1996/03/10 12:26:06 bostic Exp $ (Berkeley) $Date: 1996/03/10 12:26:06 $
+dnl	$Id: configure.in,v 8.56 1996/03/10 13:26:43 bostic Exp $ (Berkeley) $Date: 1996/03/10 13:26:43 $
 
 dnl Process this file with autoconf to produce a configure script.
 AC_INIT(configure)
@@ -67,7 +67,6 @@ dnl The default CFLAGS is -O
 CFLAGS=${CFLAGS-"-O"}
 
 dnl Checks for programs.
-SAVED_PATH=$PATH
 PATH="$PATH:/usr/bin:/usr/sbin:/sbin:/etc:/usr/etc:/usr/lib:"
 
 dnl Check for the shell path.
@@ -76,13 +75,21 @@ if test "$vi_cv_path_shell" = no; then
 	echo "Fatal error: the shell utility not found."
 	exit 1
 fi
+
 dnl Check for the sendmail path.
 AC_PATH_PROG(vi_cv_path_sendmail, sendmail, no)
 if test "$vi_cv_path_sendmail" = no; then
 	echo "Fatal error: the sendmail utility not found."
 	exit 1
 fi
-dnl Check for the /var/tmp path.
+
+dnl Check for the perl5/perl path.
+AC_PATH_PROG(vi_cv_path_perl, perl5, no)
+if test "$vi_cv_path_perl" = no; then
+	AC_PATH_PROG(vi_cv_path_perl, perl, no)
+fi
+
+dnl Check for the "preserve" path.
 AC_SUBST(vi_cv_path_preserve)
 AC_MSG_CHECKING(for preserve directory)
 AC_CACHE_VAL(vi_cv_path_preserve, [dnl
@@ -94,8 +101,7 @@ AC_CACHE_VAL(vi_cv_path_preserve, [dnl
 	else
 		vi_cv_path_preserve=no
 	fi
-	fi
-])
+	fi])
 if test "$vi_cv_path_preserve" = no; then
 	echo "Fatal error: no preserve directory found."
 	exit 1
@@ -123,8 +129,27 @@ AC_ARG_ENABLE(perlinterp,
 	[vi_cv_perlinterp="yes"], [vi_cv_perlinterp="no"])])
 AC_MSG_RESULT($vi_cv_perlinterp)
 if test "$vi_cv_perlinterp" = "yes"; then
+	if test "$vi_cv_path_perl" = no; then
+		echo "Fatal error: no perl utility found."
+		exit 1
+	fi
+	perlcppflags=`$vi_cv_path_perl -e 'use Config;print $Config{ccflags}'`
+	if test "X$perlcppflags" != "X"; then
+		CPPFLAGS="$CPPFLAGS $perlcppflags"
+	fi
+	perlarchlib=`$vi_cv_path_perl -e \
+	    'use Config;print $Config{installarchlib}."/CORE"'`
+	if test "X$perlarchlib" != "X"; then
+		CPPFLAGS="$CPPFLAGS -I$perlarchlib"
+	fi 
+	perllib=`$vi_cv_path_perl -e \
+	    'use Config;print (($Config{d_shrplib} eq "define") ? \
+	    $Config{shrpdir} : ($Config{installarchlib}."/CORE"))'`
+	if test "X$perllib" != "X"; then
+		LIBS="-L$perllib $LIBS"
+	fi
 	LIBOBJS="perl.o $LIBOBJS"
-	LIBS="-lperl $LIBS"
+	LIBS="-lperl -lm $LIBS"
 	AC_DEFINE(HAVE_PERL_INTERP)
 fi
 
