install Motif widget library, random cleanup

diff --git a/dist/Makefile.in b/dist/Makefile.in
--- a/dist/Makefile.in
+++ b/dist/Makefile.in
@@ -1,4 +1,4 @@
-#	$Id: Makefile.in,v 8.86 1996/12/11 19:26:16 bostic Exp $ (Berkeley) $Date: 1996/12/11 19:26:16 $
+#	$Id: Makefile.in,v 8.87 1996/12/12 09:06:08 bostic Exp $ (Berkeley) $Date: 1996/12/12 09:06:08 $
 
 srcdir=	@srcdir@/..
 CC=	@CC@
@@ -8,6 +8,15 @@ LDFLAGS=@LDFLAGS@
 PERL=	@vi_cv_path_perl@
 PERLLIB=@vi_cv_perllib@
 SHRPENV=@shrpenv@
+
+ar=	@vi_cv_path_ar@
+chmod=	@vi_cv_path_chmod@
+cp=	@vi_cv_path_cp@
+ln=	@vi_cv_path_ln@
+mkdir=	@vi_cv_path_mkdir@
+ranlib=	@vi_cv_path_ranlib@
+rm=	@vi_cv_path_rm@
+strip=	@vi_cv_path_strip@
 
 # Objects used to build the ex/vi editor.
 CLOBJS=	cl_bsd.o cl_funcs.o cl_main.o cl_read.o cl_screen.o cl_term.o
@@ -43,33 +52,30 @@ VIOBJS= api.o cut.o delete.o ex.o ex_abbrev.o ex_append.o ex_args.o \
 	v_word.o v_xchar.o v_yank.o v_z.o v_zexit.o vi.o vs_line.o \
 	vs_msg.o vs_refresh.o vs_relative.o vs_smap.o vs_split.o
 
-all: nvi @nvi_motif@
+all: vi @vi_motif@
 
 VIALL=	$(CLOBJS) $(IPOBJS) $(VIOBJS) @cobjs@ @LIBOBJS@
-nvi nex: $(VIALL)
+vi ex: $(VIALL)
 	$(SHRPENV) $(CC) $(LDFLAGS) -o $@ $(VIALL) @LIBS@
-	-rm -f nex
-	ln $@ nex
+	-$(rm) -f ex
+	$(ln) $@ ex
 
-M_IPC=	ipc_mcde.o ipc_mcopypaste.o ipc_mfunc.o ipc_mmain.o ipc_mmenu.o \
-	ipc_moptions.o ipc_mprompt.o ipc_msearch.o ipc_mtags.o ipc_mutil.o \
-	ipc_mvi.o xtabbed.o \
-	ip_run.o ip_send.o ip_trans.o \
-	trace.o @LIBOBJS@
-nvi_motif: $(M_IPC)
-	$(SHRPENV) $(CC) $(LDFLAGS) -o $@ $(M_IPC) @MOTIFLIBS@
+MALL=	m_main.o m_cde.o trace.o libmvi.a
+vi_motif: $(MALL)
+	$(SHRPENV) $(CC) $(LDFLAGS) -o $@ $(MALL) @MOTIFLIBS@
 
-chmod=	@vi_cv_path_chmod@
-cp=	@vi_cv_path_cp@
-ln=	@vi_cv_path_ln@
-mkdir=	@vi_cv_path_mkdir@
-rm=	@vi_cv_path_rm@
-strip=	@vi_cv_path_strip@
+MLIB=	ip_run.o ip_send.o ip_trans.o m_copypaste.o m_func.o m_menu.o \
+	m_options.o m_prompt.o m_search.o m_tags.o m_util.o m_vi.o xtabbed.o
+libmvi.a: $(MLIB)
+	$(rm) -f $@
+	$(ar) cq $@ $(MLIB)
+	[ ! -f $(ranlib) ] || $(ranlib) $@
 
 prefix=	@prefix@
 sprefix=@prefix@
 bindir=	@bindir@
 datadir=@datadir@
+libdir=	@libdir@
 mandir=	@mandir@
 exec_prefix=@exec_prefix@
 
@@ -81,58 +87,65 @@ transform=@program_transform_name@
 
 install: all install_common
 	@echo "Installing vi, ex, view: $(bindir) ..."
-	[ -d $(bindir) ] || \
+	@[ -d $(bindir) ] || \
 	    ($(mkdir) $(bindir) && $(chmod) $(dmode) $(bindir))
-	cd $(bindir) && $(rm) -f `echo vi | sed '$(transform)'`
-	$(cp) nvi $(bindir)/`echo vi | sed '$(transform)'`
-	cd $(bindir) && [ -f $(strip) ] && \
+	@cd $(bindir) && $(rm) -f `echo vi | sed '$(transform)'`
+	@$(cp) vi $(bindir)/`echo vi | sed '$(transform)'`
+	@cd $(bindir) && [ -f $(strip) ] && \
 	    $(strip) `echo vi | sed '$(transform)'`
-	cd $(bindir) && $(chmod) $(emode) `echo vi | sed '$(transform)'`
-	cd $(bindir) && $(rm) -f `echo ex | sed '$(transform)'`
-	cd $(bindir) && $(rm) -f `echo view | sed '$(transform)'`
-	cd $(bindir) && $(ln) \
+	@cd $(bindir) && $(chmod) $(emode) `echo vi | sed '$(transform)'`
+	@cd $(bindir) && $(rm) -f `echo ex | sed '$(transform)'`
+	@cd $(bindir) && $(rm) -f `echo view | sed '$(transform)'`
+	@cd $(bindir) && $(ln) \
 		`echo vi | sed '$(transform)'` `echo ex | sed '$(transform)'`
-	cd $(bindir) && $(ln) \
+	@cd $(bindir) && $(ln) \
 		`echo vi | sed '$(transform)'` `echo view | sed '$(transform)'`
-	@echo "Installing vi_motif: $(bindir) ..."
-	[ ! -f nvi_motif ] || \
-		cd $(bindir) && \
-		    $(rm) -f `echo vi_motif | sed '$(transform)'`
-	[ ! -f nvi_motif ] || \
-		$(cp) nvi_motif \
-		    $(bindir)/`echo vi_motif | sed '$(transform)'`
-	[ ! -f nvi_motif ] || \
-	        cd $(bindir) && [ -f $(strip) ] && \
-	            $(strip) `echo vi_motif | sed '$(transform)'`
-	[ ! -f nvi_motif ] || \
-	        cd $(bindir) && \
-		    $(chmod) $(emode) `echo vi_motif | sed '$(transform)'`
-	[ -d $(mandir) ] || \
+	@[ ! -f vi_motif ] || { \
+		echo "Installing vi_motif: $(bindir) ..."; \
+		(cd $(bindir) && \
+		    $(rm) -f `echo vi_motif | sed '$(transform)'`); \
+		$(cp) vi_motif \
+		    $(bindir)/`echo vi_motif | sed '$(transform)'`; \
+	        (cd $(bindir) && [ -f $(strip) ] && \
+	            $(strip) `echo vi_motif | sed '$(transform)'`); \
+	        (cd $(bindir) && \
+		    $(chmod) $(emode) `echo vi_motif | sed '$(transform)'`); \
+	}
+	@[ ! -f libmvi.a ] || { \
+		echo "Installing vi motif library: $(libdir) ..."; \
+		[ -d $(libdir) ] || \
+		    ($(mkdir) $(libdir) && $(chmod) $(dmode) $(libdir)); \
+		(cd $(libdir) && $(rm) -f libmvi.a vi_mextern.h); \
+		$(cp) -p libmvi.a \
+		    $(srcdir)/motif_l/vi_mextern.h $(libdir); \
+		(cd $(libdir) && $(chmod) $(fmode) libmvi.a vi_mextern.h); \
+	}
+	@[ -d $(mandir) ] || \
 	    ($(mkdir) $(mandir) && $(chmod) $(dmode) $(mandir))
-	[ -d $(mandir)/cat1 ] || \
+	@[ -d $(mandir)/cat1 ] || \
 	    ($(mkdir) $(mandir)/cat1 && $(chmod) $(dmode) $(mandir)/cat1)
 	@echo "Installing man pages: $(mandir) ..."
-	cd $(mandir)/cat1 && $(rm) -f `echo vi.0 | sed '$(transform)'`
-	$(cp) $(srcdir)/docs/USD.doc/vi.man/vi.0 \
+	@cd $(mandir)/cat1 && $(rm) -f `echo vi.0 | sed '$(transform)'`
+	@$(cp) $(srcdir)/docs/USD.doc/vi.man/vi.0 \
 	    $(mandir)/cat1/`echo vi.0 | sed '$(transform)'`
-	cd $(mandir)/cat1 && $(chmod) $(fmode) `echo vi.0 | sed '$(transform)'`
-	cd $(mandir)/cat1 && $(rm) -f `echo ex.0 | sed '$(transform)'`
-	cd $(mandir)/cat1 && $(rm) -f `echo view.0 | sed '$(transform)'`
-	cd $(mandir)/cat1 && $(ln) \
+	@cd $(mandir)/cat1 && $(chmod) $(fmode) `echo vi.0 | sed '$(transform)'`
+	@cd $(mandir)/cat1 && $(rm) -f `echo ex.0 | sed '$(transform)'`
+	@cd $(mandir)/cat1 && $(rm) -f `echo view.0 | sed '$(transform)'`
+	@cd $(mandir)/cat1 && $(ln) \
 	    `echo vi.0 | sed '$(transform)'` `echo ex.0 | sed '$(transform)'`
-	cd $(mandir)/cat1 && $(ln) \
+	@cd $(mandir)/cat1 && $(ln) \
 	    `echo vi.0 | sed '$(transform)'` `echo view.0 | sed '$(transform)'`
-	[ -d $(mandir)/man1 ] || \
+	@[ -d $(mandir)/man1 ] || \
 	    ($(mkdir) $(mandir)/man1 && $(chmod) $(dmode) $(mandir)/man1)
-	cd $(mandir)/man1 && $(rm) -f `echo vi.1 | sed '$(transform)'`
-	$(cp) $(srcdir)/docs/USD.doc/vi.man/vi.1 \
+	@cd $(mandir)/man1 && $(rm) -f `echo vi.1 | sed '$(transform)'`
+	@$(cp) $(srcdir)/docs/USD.doc/vi.man/vi.1 \
 	    $(mandir)/man1/`echo vi.1 | sed '$(transform)'`
-	cd $(mandir)/man1 && $(chmod) $(fmode) `echo vi.1 | sed '$(transform)'`
-	cd $(mandir)/man1 && $(rm) -f `echo ex.1 | sed '$(transform)'`
-	cd $(mandir)/man1 && $(rm) -f `echo view.1 | sed '$(transform)'`
-	cd $(mandir)/man1 && $(ln) \
+	@cd $(mandir)/man1 && $(chmod) $(fmode) `echo vi.1 | sed '$(transform)'`
+	@cd $(mandir)/man1 && $(rm) -f `echo ex.1 | sed '$(transform)'`
+	@cd $(mandir)/man1 && $(rm) -f `echo view.1 | sed '$(transform)'`
+	@cd $(mandir)/man1 && $(ln) \
 	    `echo vi.1 | sed '$(transform)'` `echo ex.1 | sed '$(transform)'`
-	cd $(mandir)/man1 && $(ln) \
+	@cd $(mandir)/man1 && $(ln) \
 	    `echo vi.1 | sed '$(transform)'` `echo view.1 | sed '$(transform)'`
 
 cat=	dutch english french german ru_SU.KOI8-R spanish swedish
@@ -142,37 +155,37 @@ install_common:
 		echo 'vi, because its value is compiled into the binaries.'; \
 		echo 'To change prefix you must reconfigure and rebuild.'; \
 		exit 1)
-	[ -f $(chmod) ]
-	[ -f $(cp) ]
-	[ -f $(ln) ]
-	[ -f $(mkdir) ]
-	[ -f $(rm) ]
-	[ -d $(prefix) ] || \
+	@[ -f $(chmod) ] || (echo 'chmod not found.'; exit 1)
+	@[ -f $(cp) ] || (echo 'cp not found.'; exit 1)
+	@[ -f $(ln) ] || (echo 'ln not found.'; exit 1)
+	@[ -f $(mkdir) ] || (echo 'mkdir not found.'; exit 1)
+	@[ -f $(rm) ] || (echo 'rm not found.'; exit 1)
+	@[ -d $(prefix) ] || \
 	    ($(mkdir) $(prefix) && $(chmod) $(dmode) $(prefix))
-	[ -d $(exec_prefix) ] || \
+	@[ -d $(exec_prefix) ] || \
 	    ($(mkdir) $(exec_prefix) && $(chmod) $(dmode) $(exec_prefix))
-	[ -d $(datadir) ] || \
+	@[ -d $(datadir) ] || \
 	    ($(mkdir) $(datadir) && $(chmod) $(dmode) $(datadir))
-	$(rm) -rf $(datadir)/vi
-	$(mkdir) $(datadir)/vi && $(chmod) $(dmode) $(datadir)/vi
+	@$(rm) -rf $(datadir)/vi
+	@$(mkdir) $(datadir)/vi && $(chmod) $(dmode) $(datadir)/vi
 	@echo "Installing message catalogs: $(datadir)/vi/catalog ..."
-	$(mkdir) $(datadir)/vi/catalog && \
+	@$(mkdir) $(datadir)/vi/catalog && \
 	    $(chmod) $(dmode) $(datadir)/vi/catalog
-	(cd $(srcdir)/catalog && $(cp) $(cat) $(datadir)/vi/catalog && \
+	@(cd $(srcdir)/catalog && $(cp) $(cat) $(datadir)/vi/catalog && \
 	    cd $(datadir)/vi/catalog && $(chmod) $(fmode) *)
 	@echo "Installing Perl scripts: $(datadir)/vi/perl ..."
-	$(mkdir) $(datadir)/vi/perl && $(chmod) $(dmode) $(datadir)/vi/perl
-	[ ! -f VI.pm ] || \
+	@$(mkdir) $(datadir)/vi/perl && $(chmod) $(dmode) $(datadir)/vi/perl
+	@[ ! -f VI.pm ] || \
 	    ($(cp) VI.pm $(datadir)/vi/perl && \
 	    (cd $(datadir)/vi/perl && $(chmod) $(fmode) VI.pm))
-	(cd $(srcdir)/perl_scripts && $(cp) *.pl $(datadir)/vi/perl && \
+	@(cd $(srcdir)/perl_scripts && $(cp) *.pl $(datadir)/vi/perl && \
 	    cd $(datadir)/vi/perl && $(chmod) $(fmode) *.pl)
 	@echo "Installing Tcl scripts: $(datadir)/vi/tcl ..."
-	$(mkdir) $(datadir)/vi/tcl && $(chmod) $(dmode) $(datadir)/vi/tcl
-	(cd $(srcdir)/tcl_scripts && $(cp) *.tcl $(datadir)/vi/tcl && \
+	@$(mkdir) $(datadir)/vi/tcl && $(chmod) $(dmode) $(datadir)/vi/tcl
+	@(cd $(srcdir)/tcl_scripts && $(cp) *.tcl $(datadir)/vi/tcl && \
 	    cd $(datadir)/vi/tcl && $(chmod) $(fmode) *.tcl)
 	@echo "Installing recover script: $(datadir)/vi/recover ..."
-	($(cp) recover $(datadir)/vi/recover && \
+	@($(cp) recover $(datadir)/vi/recover && \
 	    $(chmod) $(emode) $(datadir)/vi/recover)
 
 uninstall:
@@ -196,7 +209,7 @@ docs:
 
 clean:
 	-rm -f *.core *.o memcpy.c perl.c
-	-rm -f nex nvi nvi_motif core
+	-rm -f vi ex vi_motif core
 	-rm -f $(COBJS) $(CLOBJS) $(DBOBJS) $(REOBJS)
 	-rm -f $(TKOBJS) $(VIOBJS)
 
@@ -226,22 +239,21 @@ cl_term.o: $(srcdir)/cl/cl_term.c
 	$(CC) $(CFLAGS) $?
 
 # Vi IP sources.
-ip_funcs.o: $(srcdir)/ip_vi/ip_funcs.c
+ip_funcs.o: $(srcdir)/ip/ip_funcs.c
 	$(CC) $(CFLAGS) $?
-ip_main.o: $(srcdir)/ip_vi/ip_main.c
+ip_main.o: $(srcdir)/ip/ip_main.c
 	$(CC) $(CFLAGS) $?
-ip_read.o: $(srcdir)/ip_vi/ip_read.c
+ip_read.o: $(srcdir)/ip/ip_read.c
 	$(CC) $(CFLAGS) $?
-ip_screen.o: $(srcdir)/ip_vi/ip_screen.c
+ip_screen.o: $(srcdir)/ip/ip_screen.c
 	$(CC) $(CFLAGS) $?
-ip_term.o: $(srcdir)/ip_vi/ip_term.c
+ip_term.o: $(srcdir)/ip/ip_term.c
 	$(CC) $(CFLAGS) $?
 
 # VI is the binary that the client programs run.
 VI=-DVI=\"$(bindir)/`echo vi | sed '$(transform)'`\"
 
 # Shared IP client sources.
-$(srcdir)/ipc/ip_run.c: Makefile
 ip_run.o: $(srcdir)/ipc/ip_run.c
 	$(CC) $(VI) $(CFLAGS) $?
 ip_send.o: $(srcdir)/ipc/ip_send.c
@@ -249,30 +261,32 @@ ip_send.o: $(srcdir)/ipc/ip_send.c
 ip_trans.o: $(srcdir)/ipc/ip_trans.c
 	$(CC) $(CFLAGS) $?
 
+# Motif IP standalone sources.
+m_main.o: $(srcdir)/motif/m_main.c
+	$(CC) $(CFLAGS) @XINCS@ $?
+m_cde.o: $(srcdir)/motif/m_cde.c
+	$(CC) $(CFLAGS) @XINCS@ $?
+
 # Motif IP client sources.
-ipc_mcde.o: $(srcdir)/ipc_motif/ipc_mcde.c
+m_copypaste.o: $(srcdir)/motif_l/m_copypaste.c
 	$(CC) $(CFLAGS) @XINCS@ $?
-ipc_mcopypaste.o: $(srcdir)/ipc_motif/ipc_mcopypaste.c
+m_func.o: $(srcdir)/motif_l/m_func.c
 	$(CC) $(CFLAGS) @XINCS@ $?
-ipc_mfunc.o: $(srcdir)/ipc_motif/ipc_mfunc.c
+m_options.o: $(srcdir)/motif_l/m_options.c
 	$(CC) $(CFLAGS) @XINCS@ $?
-ipc_mmain.o: $(srcdir)/ipc_motif/ipc_mmain.c
+m_menu.o: $(srcdir)/motif_l/m_menu.c
 	$(CC) $(CFLAGS) @XINCS@ $?
-ipc_moptions.o: $(srcdir)/ipc_motif/ipc_moptions.c
+m_prompt.o: $(srcdir)/motif_l/m_prompt.c
 	$(CC) $(CFLAGS) @XINCS@ $?
-ipc_mmenu.o: $(srcdir)/ipc_motif/ipc_mmenu.c
+m_search.o: $(srcdir)/motif_l/m_search.c
 	$(CC) $(CFLAGS) @XINCS@ $?
-ipc_mprompt.o: $(srcdir)/ipc_motif/ipc_mprompt.c
+m_tags.o: $(srcdir)/motif_l/m_tags.c
 	$(CC) $(CFLAGS) @XINCS@ $?
-ipc_msearch.o: $(srcdir)/ipc_motif/ipc_msearch.c
+m_util.o: $(srcdir)/motif_l/m_util.c
 	$(CC) $(CFLAGS) @XINCS@ $?
-ipc_mtags.o: $(srcdir)/ipc_motif/ipc_mtags.c
+m_vi.o: $(srcdir)/motif_l/m_vi.c
 	$(CC) $(CFLAGS) @XINCS@ $?
-ipc_mutil.o: $(srcdir)/ipc_motif/ipc_mutil.c
-	$(CC) $(CFLAGS) @XINCS@ $?
-ipc_mvi.o: $(srcdir)/ipc_motif/ipc_mvi.c
-	$(CC) $(CFLAGS) @XINCS@ $?
-xtabbed.o: $(srcdir)/ipc_motif/xtabbed.c
+xtabbed.o: $(srcdir)/motif_l/xtabbed.c
 	$(CC) $(CFLAGS) @XINCS@ $?
 
 # Vi Tcl/Perl interpreter sources.
